# Block
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_core.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to128_multiplier.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to128_multiplier_badpipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_multiplier_gcm_spec.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/m0_table_generator.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/r_table_generator.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/multiplier.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/ghash_core_koa_parallel.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/ghash_core_koa_pipe_parallel.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/polinomial_mult_koa.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/gf_2to128_multiplier_booth1_subrem.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/polinomial_mult_koa_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/polinomial_mult_koa_optimized_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/polinomial_mult_koa_optimized_pipe_recursive.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/multiplier_without_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/ghash_core_koa_feedback_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/ghash_core_koa.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/ghash_core_koa_n_blocks.v
$PROJ_COMMON_RTL_UTILS/common_generated_xor_line.v
$PROJ_COMMON_RTL_UTILS/common_generated_xor_tree.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_koa_generated.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_koa_merger.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_koa_merger_line.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_koa_splitter.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_koa_splitter_line.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2toN_multiplier_no_rem.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_new_architecture.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_new_arch_pipelined.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_stage1_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_stage2_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_stage3_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_msg_and_h_pow_picker.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_control_signal_unit.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gcm_aes_core2.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_wrapper.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/key_scheduler_sequential_shifter.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/key_scheduler_sequential_nwords.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/key_scheduler_sequential_1word.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to128_multiplier_sequential.v
$PROJ_COMMON_RTL_UTILS/common_flag_check.v
$PROJ_COMMON_RTL_UTILS/common_posedge_det.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/common_fix_delay_line_w_del_valid.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/xtime_new.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/time_03_new.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ax_modular_multiplier_new.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/mixcolumns_block_new.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gcm_aes_core_1gctr_2.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pipelined_ghash/h_key_power_table.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_koa_n_blocks.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gctr_function_n_blocks.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gctr_function_n_blocks_xor_data.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/inc32_block.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/aes_round_ladder.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/aes_round_ladder_xor_data.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/round_block.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/round_block_and_pipe.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/subbytes_block.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/shiftrows_block.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/mixcolumns_block.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/common_fix_delay_line_w_valid.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/byte_substitution_box.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ax_modular_multiplier.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/time_03.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/xtime.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/key_scheduler.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/byte_inverse_isomorphic_mapping.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/byte_isomorphic_mapping.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/aes_round_ladder_sequential.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/round_block_sequential.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gctr_function_n_blocks_xor_data.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/aes_round_ladder_xor_data.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/round_block_and_pipe.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gcm_aes_cipher.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/j0_generator.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/pulse_sequencer_fsm.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/subkey_h_powers_generator.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gcm_aes_cipher_tag_fsm.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/ghash_koa_n_blocks.v

$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gcm_aes_core_1gctr.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gctr_function_n_blocks_xor_data_shared.v


$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/byte_substitution_algorithm.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to2_multiplier.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to2_multiplier_with_constant_phi.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to4_multiplicative_inversion.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to4_multiplier.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to4_multiplier_with_constant_lambda.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/gf_2to4_squarer.v
$PROJ_COMMON_RTL_LIBRARY/ghash_core/rtl/multiplicative_inversion.v
